# Generated by Django 3.0.3 on 2020-02-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoatifyApp', '0002_auto_20200211_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
