# Generated by Django 3.0.3 on 2020-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoatifyApp', '0003_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('fare', models.IntegerField()),
            ],
        ),
    ]
