# Generated by Django 3.0.3 on 2020-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoatifyApp', '0004_schedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
    ]
