# Generated by Django 3.0.3 on 2020-02-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoatifyApp', '0006_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
