# Generated by Django 3.0.3 on 2020-02-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoatifyApp', '0007_delete_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='boatid',
            field=models.IntegerField(default=0),
        ),
    ]
