# Generated by Django 3.0.3 on 2020-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seatres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boatid', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('seatid', models.CharField(max_length=50)),
            ],
        ),
    ]
